# Generated by Django 5.2 on 2025-05-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='confirm_password',
        ),
    ]
